set(common --recipe "${RECIPE}" --tile 16 24 32 --slots 2 2 3 --snapshot-reservation 4194304)
function(check_plan expected grid_limit voxel_size)
  execute_process(COMMAND "${PLAN_TOOL}" ${common} --voxel-size "${voxel_size}"
    --limits "${grid_limit}" 67108864 33554432 33554432 8388608 1207959552
    RESULT_VARIABLE code OUTPUT_VARIABLE report ERROR_VARIABLE errors)
  if(NOT code EQUAL expected)
    message(FATAL_ERROR "Plan CLI exit ${code}, expected ${expected}: ${errors}\n${report}")
  endif()
  if(expected EQUAL 1)
    string(JSON error GET "${report}" error)
    if(error STREQUAL "")
      message(FATAL_ERROR "Invalid-input report did not include an error")
    endif()
  else()
    string(JSON jobs GET "${report}" generation_jobs)
    string(JSON fits GET "${report}" modeled_reservations_fit)
    if(NOT jobs EQUAL 0)
      message(FATAL_ERROR "Resource CLI invoked generation")
    endif()
    if(expected EQUAL 0 AND NOT fits)
      message(FATAL_ERROR "Valid resource plan did not fit")
    elseif(expected EQUAL 2)
      string(JSON category GET "${report}" exceeded_categories 0)
      if(fits OR NOT category STREQUAL "cpu_dense_grid")
        message(FATAL_ERROR "Over-budget CLI did not identify the grid limit")
      endif()
    endif()
  endif()
endfunction()
check_plan(0 1073741824 3)
check_plan(2 1 3)
check_plan(1 1073741824 nan)
check_plan(1 1073741824 0)
message(STATUS "Plan CLI JSON, exact success/budget/error exits and zero generation PASS")
